### ISSUE TITLE
“Comments”

### ISSUE THREAD

**Issue by flying-sheep** [Bioconductor/UniProt.ws#10] opened 2019-08-16 09:26 UTC
The information I’m interested doesn’t seem to be retrieved. When I fetch the “COMMENTS” column, I get something useless like:

```r
> AnnotationDbi::select(up, entrez_ids, 'COMMENTS', 'ENTREZ_GENE')$COMMENTS
'Developmental stage (1); Function (1); Induction (1); Sequence similarities (1); Subcellular location (1); Tissue specificity (1)'
```

“Subcellular location” seems to be there, but not everything.

**Comment by mtmorgan** [comment] 2019-08-16 11:12
can you provide a more complete statement of your problem, with a reproducible (i.e., I can cut and paste your commands into my session, and see the problem) example and some indication of what you would expect and why?

**Comment by flying-sheep** [comment] 2019-08-16 11:24
This is a feature request, not a bug, so there’s no reproducible example.

My specific request would be that I want “Tissue specificity” among the selectable columns, but I think all possible “comments” should be there.

**Comment by mtmorgan** [comment] 2019-08-16 11:47
I'm still looking for more specific information from you, so that I don't provide the wrong information. For instance, in the above, what specific `entrez_ids` are you using, and from I guess the UniProt web site how do you know the information you want is available?

**Comment by flying-sheep** [comment] 2019-08-16 14:08
e.g. [those](https://www.uniprot.org/uniprot/?query=Q7TPG8+OR+P63318) have the “Tissue specificity” field. So I’d like for this to return something useful

```r
> up <- UniProt.ws(10090)
> select(up, c('Q7TPG8', 'P63318'), 'TISSUE-SPECIFICITY', 'UNIPROTKB')
```

All available columns can be seen [here](https://www.uniprot.org/help/uniprotkb_column_names) and should probably taken from there instead of a hardcoded file.

**Comment by LiNk-NY** [comment] 2021-08-26 15:41
@Kayla-Morrell @mtmorgan 
I was looking into this a bit due to a related issue and came up with this to get the available columns from the website:

``` r
suppressPackageStartupMessages(library(rvest))
aa <- read_html("https://www.uniprot.org/help/uniprotkb_column_names")
tabs <- html_table(aa)
tnames <- html_nodes(aa, css = "h3[id]") %>% html_text()
names(tabs) <- tnames
tabs
#> $`Names & Taxonomy`
#> # A tibble: 13 × 2
#>    `Column names as displayed on website` `Column names as displayed in URL`
#>    <chr>                                  <chr>                             
#>  1 Entry                                  id                                
#>  2 Entry name                             entry name                        
#>  3 Gene names                             genes                             
#>  4 Gene names (primary)                   genes(PREFERRED)                  
#>  5 Gene names (synonym)                   genes(ALTERNATIVE)                
#>  6 Gene names (ordered locus)             genes(OLN)                        
#>  7 Gene names (ORF)                       genes(ORF)                        
#>  8 Organism                               organism                          
#>  9 Organism ID                            organism-id                       
#> 10 Protein names                          protein names                     
#> 11 Proteomes                              proteome                          
#> 12 Taxonomic lineage                      lineage(ALL)                      
#> 13 Virus hosts                            virus hosts                       
#> 
#> $Sequences
#> # A tibble: 23 × 2
#>    `Column names as displayed on website` `Column names as displayed in URL`    
#>    <chr>                                  <chr>                                 
#>  1 Fragment                               fragment                              
#>  2 Gene encoded by                        encodedon                             
#>  3 Alternative products                   comment(ALTERNATIVE PRODUCTS)         
#>  4 Erroneous gene model prediction        comment(ERRONEOUS GENE MODEL PREDICTI…
#>  5 Erroneous initiation                   comment(ERRONEOUS INITIATION)         
#>  6 Erroneous termination                  comment(ERRONEOUS TERMINATION)        
#>  7 Erroneous translation                  comment(ERRONEOUS TRANSLATION)        
#>  8 Frameshift                             comment(FRAMESHIFT)                   
#>  9 Mass spectrometry                      comment(MASS SPECTROMETRY)            
#> 10 Polymorphism                           comment(POLYMORPHISM)                 
#> # … with 13 more rows
[ truncated ... ]
```

<sup>Created on 2021-08-26 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 4.1.1 Patched (2021-08-22 r80813)
#>  os       Ubuntu 20.10                               
#>  system   x86_64, linux-gnu                          
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_US.UTF-8                                
#>  ctype    en_US.UTF-8                                
#>  tz       America/New_York                           
#>  date     2021-08-26                                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  backports     1.2.1   2020-12-09 [1] CRAN (R 4.1.0)
#>  cli           3.0.1   2021-07-17 [1] RSPM (R 4.1.0)
#>  crayon        1.4.1   2021-02-08 [1] CRAN (R 4.1.0)
#>  curl          4.3.2   2021-06-23 [1] RSPM (R 4.1.0)
#>  digest        0.6.27  2020-10-24 [1] RSPM (R 4.1.0)
#>  ellipsis      0.3.2   2021-04-29 [1] RSPM (R 4.2.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
#>  fansi         0.5.0   2021-05-25 [1] RSPM (R 4.1.0)
#>  fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
#>  glue          1.4.2   2020-08-27 [1] CRAN (R 4.1.0)
#>  highr         0.9     2021-04-16 [1] RSPM (R 4.2.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.1.0)
#>  httr          1.4.2   2020-07-20 [1] CRAN (R 4.1.0)
#>  knitr         1.33    2021-04-24 [1] RSPM (R 4.2.0)
#>  lifecycle     1.0.0   2021-02-15 [1] RSPM (R 4.1.0)
#>  magrittr      2.0.1   2020-11-17 [1] RSPM (R 4.1.0)
#>  pillar        1.6.2   2021-07-29 [1] RSPM (R 4.1.0)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.1.0)
#>  R6            2.5.1   2021-08-19 [1] RSPM (R 4.1.1)
#>  reprex        2.0.1   2021-08-05 [1] RSPM (R 4.1.0)
#>  rlang         0.4.11  2021-04-30 [1] RSPM (R 4.2.0)
#>  rmarkdown     2.10    2021-08-06 [1] RSPM (R 4.1.0)
#>  rvest       * 1.0.1   2021-07-26 [1] RSPM (R 4.1.0)
#>  selectr       0.4-2   2019-11-20 [1] CRAN (R 4.1.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
#>  stringi       1.7.3   2021-07-16 [1] RSPM (R 4.1.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.1.0)
#>  styler        1.5.1   2021-07-13 [1] RSPM (R 4.1.0)
#>  tibble        3.1.3   2021-07-23 [1] RSPM (R 4.1.0)
#>  utf8          1.2.2   2021-07-24 [1] RSPM (R 4.1.0)
#>  vctrs         0.3.8   2021-04-29 [1] RSPM (R 4.2.0)
#>  withr         2.4.2   2021-04-18 [1] RSPM (R 4.2.0)
#>  xfun          0.25    2021-08-06 [1] RSPM (R 4.1.0)
#>  xml2          1.3.2   2020-04-23 [1] CRAN (R 4.1.0)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)
#> 
#> [1] /media/mr148/1D24A0EA4286043C1/bioc-devel
#> [2] /home/mr148/src/svn/r-release/R/lib/R/library
```

</details>

**Comment by LiNk-NY** [comment] 2022-08-10 14:19
@flying-sheep 
This is resolved in the new version of the package. 
See version `1.37.1`

```r
select(up, c('Q7TPG8', 'P63318'), c("accession", "id", "organism_name", "cc_tissue_specificity"), "UniProtKB")
    From  Entry  Entry.Name             Organism
1 Q7TPG8 Q7TPG8 TAFA1_MOUSE Mus musculus (Mouse)
2 P63318 P63318  KPCG_MOUSE Mus musculus (Mouse)
                                                                                                                                                                                    Tissue.specificity
1                                                                  TISSUE SPECIFICITY: Expressed in the hippocampus and detected also in the cortex (at protein level). {ECO:0000269|PubMed:29799787}.
2 TISSUE SPECIFICITY: Expressed in the cerebellum, cerebral cortex and hippocampus (at protein level). Highly expressed in Purkinje cells. {ECO:0000269|PubMed:17904530, ECO:0000269|PubMed:23185022}.

```

**Closed as completed by LiNk-NY** 2022-08-10 14:19 UTC
